context:
  version: "0.7.2"

package:
  name: dioxus
  version: ${{ version }}

source:
  url: https://github.com/DioxusLabs/dioxus/archive/v${{ version }}.tar.gz
  sha256: f37e526f0d206f871c10d38bcab4b09d33f483ef4ebd20ecaa2a8a4190f0e746

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - libgit2  # only used for a build binary
    - make
    - pkg-config
  host:
    - openssl

tests:
  - script:
      - dx --help

about:
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Fullstack app framework for web, desktop, mobile, and more.
  homepage: https://github.com/DioxusLabs/dioxus
  repository: https://github.com/DioxusLabs/dioxus

extra:
  recipe-maintainers:
    - danielnachun
