context:
  version: "0.7.6"

package:
  name: dioxus
  version: ${{ version }}

source:
  url: https://github.com/DioxusLabs/dioxus/archive/v${{ version }}.tar.gz
  sha256: 539a4b9cc5905da57f75520bffb2eb0f69e064cb769178731ed078b862bed9ad

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - make
    - pkg-config
  host:
    - openssl
    - if: win
      then: libssh2

tests:
  - script:
      - dx --help

about:
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Fullstack app framework for web, desktop, mobile, and more.
  homepage: https://github.com/DioxusLabs/dioxus
  repository: https://github.com/DioxusLabs/dioxus

extra:
  recipe-maintainers:
    - danielnachun
