context:
  version: "0.6.1"

package:
  name: dioxus
  version: ${{ version }}

source:
  url: https://github.com/DioxusLabs/dioxus/archive/v${{ version }}.tar.gz
  sha256: 5f469a0209785c96e412f28e6d67962853903b6b743824c7ddd2405e7b71408e

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - make
    - pkg-config
  host:
    - openssl

tests:
  - script:
      - dx --help

about:
  license: Apache-2.0 AND MIT
  license_file:
    - LICENSE-APACHE
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: Fullstack app framework for web, desktop, mobile, and more.
  homepage: https://github.com/DioxusLabs/dioxus
  repository: https://github.com/DioxusLabs/dioxus

extra:
  recipe-maintainers:
    - danielnachun
